// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb49S81pRSzUVpSQd_b1O2V85DC-YEBVc',
    appId: '1:16925559188:web:1b275779250c8e9ace6781',
    messagingSenderId: '16925559188',
    projectId: 'orbit-1dc5f',
    authDomain: 'orbit-1dc5f.firebaseapp.com',
    storageBucket: 'orbit-1dc5f.firebasestorage.app',
    measurementId: 'G-YPETLC4KW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU6BDsAxy_Q3jBNHI5FpCufRPD2zo8sVc',
    appId: '1:16925559188:android:c0854c024d063103ce6781',
    messagingSenderId: '16925559188',
    projectId: 'orbit-1dc5f',
    storageBucket: 'orbit-1dc5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8daxsuWyjS9NfaRKmnbnGtPXXVjKssi0',
    appId: '1:16925559188:ios:1fcbe62d225d01b4ce6781',
    messagingSenderId: '16925559188',
    projectId: 'orbit-1dc5f',
    storageBucket: 'orbit-1dc5f.firebasestorage.app',
    iosBundleId: 'com.example.orbit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8daxsuWyjS9NfaRKmnbnGtPXXVjKssi0',
    appId: '1:16925559188:ios:1fcbe62d225d01b4ce6781',
    messagingSenderId: '16925559188',
    projectId: 'orbit-1dc5f',
    storageBucket: 'orbit-1dc5f.firebasestorage.app',
    iosBundleId: 'com.example.orbit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb49S81pRSzUVpSQd_b1O2V85DC-YEBVc',
    appId: '1:16925559188:web:d039626a4ec8f252ce6781',
    messagingSenderId: '16925559188',
    projectId: 'orbit-1dc5f',
    authDomain: 'orbit-1dc5f.firebaseapp.com',
    storageBucket: 'orbit-1dc5f.firebasestorage.app',
    measurementId: 'G-KZ69306WZR',
  );
}
